image: python

stages:
  - test
  - build
  - deploy

# --- 1) TESTS ---
unit-test:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m unittest test.py

# --- 2) BUILD & PUSH DOCKER IMAGE ---
# CI_REGISTRY, CI_REGISTRY_USER, CI_REGISTRY_PASSWORD, CI_REGISTRY_IMAGE, CI_COMMIT_SHA
# sont fournis nativement par GitLab Runner
build-docker-image:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
  after_script:
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - develop
  needs:
    - unit-test

# --- 3) DEPLOY (Coolify webhook) ---
deploy-job:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "Triggering Coolify deployment..."
    - >
      curl --location --request POST "$COOLIFY_WEBHOOK" \
         --header "Authorization: Bearer $TOKEN" \
         --header "Content-Type: application/json" \
         --data '{}'
  needs:
    - build-docker-image
  when: manual
  only:
    - develop